services:
    n0c.s3_client:
        class: Aws\S3\S3Client
        arguments:
            -
                version: 'latest'
                region: '%env(string:N0C_REGION)%'
                endpoint: '%env(string:N0C_ENDPOINT)%'
                use_path_style_endpoint: true
                signature_version: 'v4'
                credentials:
                    key: '%env(string:N0C_ACCESS_KEY)%'
                    secret: '%env(string:N0C_SECRET_KEY)%'

flysystem:
    storages:
        avatars.storage:
            visibility: public
            aws:
                client: 'n0c.s3_client'
                bucket: '%env(string:N0C_BUCKET)%'
                prefix: 'Public/images/avatar'
                streamReads: true

        biens.storage:
            visibility: public
            aws:
                client: 'n0c.s3_client'
                bucket: '%env(string:N0C_BUCKET)%'
                prefix: 'Public/images/bien'
                streamReads: true