vich_uploader:
    db_driver: orm
    storage: file_system

    metadata:
        type: attribute

    mappings:
        avatars:
            uri_prefix: /images/avatars
            upload_destination: '%kernel.project_dir%/public/images/avatars'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true

        biens:
            uri_prefix: /images/properties
            upload_destination: '%kernel.project_dir%/public/images/properties'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true