vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        avatars:
            uri_prefix: /images/avatars
            upload_destination: '%kernel.project_dir%/public/images/avatars'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        biens:
            uri_prefix: /images/biens
            upload_destination: '%kernel.project_dir%/public/images/biens'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            directory_namer: App\Vich\PropertyDirectoryNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true


