vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    storage: flysystem

    mappings:
        avatars:
            uri_prefix: '%env(string:N0C_PUBLIC_URL)%/avatar'
            upload_destination: 'avatars.storage'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        biens:
            uri_prefix: '%env(string:N0C_PUBLIC_URL)%/bien'
            upload_destination: 'biens.storage'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            directory_namer: App\Vich\PropertyDirectoryNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true