<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260901140928 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs

        // Force InnoDB even when the server default engine is MyISAM/Aria
        // (some shared hosts): a MyISAM index caps at 1000 bytes, which several
        // utf8mb4 VARCHAR(255) indexes below exceed. Each CREATE TABLE also
        // pins "ENGINE = InnoDB ROW_FORMAT = DYNAMIC" explicitly.
        $this->addSql('SET SESSION default_storage_engine = \'InnoDB\'');

        $this->addSql('CREATE TABLE agency_billing_profile (id INT AUTO_INCREMENT NOT NULL, stripe_customer_id VARCHAR(255) DEFAULT NULL, billing_email VARCHAR(255) DEFAULT NULL, legal_name VARCHAR(255) DEFAULT NULL, commercial_name VARCHAR(255) DEFAULT NULL, address_line1 VARCHAR(255) DEFAULT NULL, address_line2 VARCHAR(255) DEFAULT NULL, postal_code VARCHAR(30) DEFAULT NULL, city VARCHAR(150) DEFAULT NULL, region VARCHAR(150) DEFAULT NULL, country_code VARCHAR(2) DEFAULT NULL, locale VARCHAR(10) DEFAULT \'fr\' NOT NULL, tax_exempt_status VARCHAR(30) DEFAULT \'none\' NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, agency_id INT NOT NULL, preferred_currency_id INT DEFAULT NULL, default_payment_method_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_7F37F400708DC647 (stripe_customer_id), UNIQUE INDEX UNIQ_7F37F400CDEADB2A (agency_id), INDEX IDX_7F37F4007A5B1307 (preferred_currency_id), UNIQUE INDEX UNIQ_7F37F400AF212FD0 (default_payment_method_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE agency_notification (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) NOT NULL, date DATETIME NOT NULL, read_at DATETIME DEFAULT NULL, agency_id INT NOT NULL, INDEX IDX_30AE0EFCDEADB2A (agency_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE agency_payment_method (id INT AUTO_INCREMENT NOT NULL, stripe_payment_method_id VARCHAR(255) NOT NULL, stripe_setup_intent_id VARCHAR(255) DEFAULT NULL, stripe_mandate_id VARCHAR(255) DEFAULT NULL, type VARCHAR(30) NOT NULL, brand VARCHAR(50) DEFAULT NULL, last4 VARCHAR(4) DEFAULT NULL, exp_month INT DEFAULT NULL, exp_year INT DEFAULT NULL, cardholder_name VARCHAR(255) DEFAULT NULL, country_code VARCHAR(2) DEFAULT NULL, funding VARCHAR(30) DEFAULT NULL, fingerprint VARCHAR(255) DEFAULT NULL, is_default TINYINT DEFAULT 0 NOT NULL, is_active TINYINT DEFAULT 1 NOT NULL, setup_status VARCHAR(30) NOT NULL, detached_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, billing_profile_id INT NOT NULL, UNIQUE INDEX UNIQ_8AFEFB3E2D13D9D5 (stripe_payment_method_id), INDEX IDX_8AFEFB3E409D7D29 (billing_profile_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE agency_profile_daily_visit (id INT AUTO_INCREMENT NOT NULL, viewed_on DATE NOT NULL, visits INT DEFAULT 0 NOT NULL, agency_id INT NOT NULL, INDEX IDX_507FAD7ECDEADB2A (agency_id), UNIQUE INDEX uniq_agency_profile_daily_visit (agency_id, viewed_on), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE agency_subscription (id INT AUTO_INCREMENT NOT NULL, status VARCHAR(30) NOT NULL, started_at DATETIME NOT NULL, current_period_start DATETIME DEFAULT NULL, current_period_end DATETIME DEFAULT NULL, cancel_at_period_end TINYINT DEFAULT 0 NOT NULL, canceled_at DATETIME DEFAULT NULL, cancel_requested_at DATETIME DEFAULT NULL, ended_at DATETIME DEFAULT NULL, provider_customer_id VARCHAR(255) DEFAULT NULL, provider_subscription_id VARCHAR(255) DEFAULT NULL, provider_subscription_item_id VARCHAR(255) DEFAULT NULL, provider_price_id VARCHAR(255) DEFAULT NULL, provider_product_id VARCHAR(255) DEFAULT NULL, provider_latest_invoice_id VARCHAR(255) DEFAULT NULL, provider_schedule_id VARCHAR(255) DEFAULT NULL, pending_plan_change_effective_at DATETIME DEFAULT NULL, pending_plan_change_requested_at DATETIME DEFAULT NULL, payment_failure_count INT DEFAULT 0 NOT NULL, first_payment_failure_at DATETIME DEFAULT NULL, last_payment_failure_at DATETIME DEFAULT NULL, next_payment_retry_at DATETIME DEFAULT NULL, payment_recovery_deadline DATETIME DEFAULT NULL, last_successful_payment_at DATETIME DEFAULT NULL, last_stripe_sync_at DATETIME DEFAULT NULL, property_limit_snapshot INT DEFAULT NULL, included_boosts_snapshot INT DEFAULT 0 NOT NULL, boost_duration_days_snapshot INT DEFAULT 7 NOT NULL, amount_snapshot_minor BIGINT DEFAULT 0 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, agency_id INT NOT NULL, plan_id INT NOT NULL, plan_price_id INT DEFAULT NULL, pending_plan_price_id INT DEFAULT NULL, currency_snapshot_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_1F98F2F6424D71C9 (provider_subscription_id), INDEX IDX_1F98F2F6CDEADB2A (agency_id), INDEX IDX_1F98F2F6E899029B (plan_id), INDEX IDX_1F98F2F6D871F09D (plan_price_id), INDEX IDX_1F98F2F6AE027C2 (pending_plan_price_id), INDEX IDX_1F98F2F6CAD137FF (currency_snapshot_id), INDEX idx_agency_subscription_status_period_end (status, current_period_end), INDEX idx_agency_subscription_retry (status, next_payment_retry_at), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE agency_subscription_period (id INT AUTO_INCREMENT NOT NULL, period_start DATETIME NOT NULL, period_end DATETIME NOT NULL, property_limit INT DEFAULT NULL, included_boosts INT DEFAULT 0 NOT NULL, amount_minor BIGINT DEFAULT 0 NOT NULL, status VARCHAR(30) NOT NULL, provider_invoice_id VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, subscription_id INT NOT NULL, currency_id INT NOT NULL, payment_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_8A7365A4C3FBD45 (provider_invoice_id), INDEX IDX_8A7365A49A1887DC (subscription_id), INDEX IDX_8A7365A438248176 (currency_id), INDEX IDX_8A7365A44C3A3BB (payment_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE billing_tax_identifier (id INT AUTO_INCREMENT NOT NULL, type VARCHAR(50) NOT NULL, country_code VARCHAR(2) NOT NULL, value VARCHAR(255) NOT NULL, stripe_tax_id VARCHAR(255) DEFAULT NULL, verification_status VARCHAR(30) NOT NULL, is_primary TINYINT DEFAULT 0 NOT NULL, verified_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, billing_profile_id INT NOT NULL, UNIQUE INDEX UNIQ_247C4B011AE559E4 (stripe_tax_id), INDEX IDX_247C4B01409D7D29 (billing_profile_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE booster_pack (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(150) NOT NULL, description LONGTEXT DEFAULT NULL, boost_quantity INT NOT NULL, boost_duration_days INT DEFAULT 7 NOT NULL, is_active TINYINT DEFAULT 1 NOT NULL, position INT DEFAULT 0 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_2EF57F2C77153098 (code), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE booster_pack_price (id INT AUTO_INCREMENT NOT NULL, amount_minor BIGINT NOT NULL, payment_provider_price_id VARCHAR(255) DEFAULT NULL, is_active TINYINT DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, booster_pack_id INT NOT NULL, currency_id INT NOT NULL, UNIQUE INDEX UNIQ_C877F169B2C0EFFF (payment_provider_price_id), INDEX IDX_C877F16932661930 (booster_pack_id), INDEX IDX_C877F16938248176 (currency_id), UNIQUE INDEX uniq_booster_pack_currency (booster_pack_id, currency_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE booster_transaction (id INT AUTO_INCREMENT NOT NULL, quantity INT NOT NULL, type VARCHAR(40) NOT NULL, expires_at DATETIME DEFAULT NULL, idempotency_key VARCHAR(255) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, agency_id INT NOT NULL, property_id INT DEFAULT NULL, booster_pack_id INT DEFAULT NULL, subscription_period_id INT DEFAULT NULL, payment_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_9EE4BCAE7FD1C147 (idempotency_key), INDEX IDX_9EE4BCAECDEADB2A (agency_id), INDEX IDX_9EE4BCAE549213EC (property_id), INDEX IDX_9EE4BCAE32661930 (booster_pack_id), INDEX IDX_9EE4BCAEDE34B862 (subscription_period_id), INDEX IDX_9EE4BCAE4C3A3BB (payment_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE caracteristique (id INT AUTO_INCREMENT NOT NULL, icone VARCHAR(255) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE caracteristique_translation (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) NOT NULL, locale VARCHAR(5) NOT NULL, translatable_id INT DEFAULT NULL, INDEX IDX_9AB160AD2C2AC5D3 (translatable_id), UNIQUE INDEX caracteristique_translation_unique_translation (translatable_id, locale), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE category_bien (id INT AUTO_INCREMENT NOT NULL, icone VARCHAR(255) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE category_bien_transaction (id INT AUTO_INCREMENT NOT NULL, icone VARCHAR(255) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE category_bien_transaction_translation (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, locale VARCHAR(5) NOT NULL, translatable_id INT DEFAULT NULL, INDEX IDX_96E036FE2C2AC5D3 (translatable_id), UNIQUE INDEX category_bien_transaction_translation_unique_translation (translatable_id, locale), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE category_bien_translation (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, locale VARCHAR(5) NOT NULL, translatable_id INT DEFAULT NULL, INDEX IDX_8E410EED2C2AC5D3 (translatable_id), UNIQUE INDEX category_bien_translation_unique_translation (translatable_id, locale), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE contact (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(100) NOT NULL, prenom VARCHAR(100) NOT NULL, email VARCHAR(180) NOT NULL, message LONGTEXT NOT NULL, created_at DATETIME NOT NULL, agence_id INT DEFAULT NULL, INDEX IDX_4C62E638D725330D (agence_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE credit_note (id INT AUTO_INCREMENT NOT NULL, number VARCHAR(100) NOT NULL, status VARCHAR(20) NOT NULL, reason VARCHAR(255) NOT NULL, subtotal_minor BIGINT NOT NULL, tax_total_minor BIGINT NOT NULL, total_minor BIGINT NOT NULL, seller_snapshot JSON NOT NULL, customer_snapshot JSON NOT NULL, provider_credit_note_id VARCHAR(255) DEFAULT NULL, issued_at DATETIME DEFAULT NULL, voided_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, invoice_id INT NOT NULL, refund_id INT DEFAULT NULL, currency_id INT NOT NULL, UNIQUE INDEX UNIQ_C87F452996901F54 (number), UNIQUE INDEX UNIQ_C87F452944B4A0D2 (provider_credit_note_id), INDEX IDX_C87F45292989F1FD (invoice_id), UNIQUE INDEX UNIQ_C87F4529189801D5 (refund_id), INDEX IDX_C87F452938248176 (currency_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE credit_note_line (id INT AUTO_INCREMENT NOT NULL, description VARCHAR(255) NOT NULL, quantity NUMERIC(12, 3) NOT NULL, unit_amount_minor BIGINT NOT NULL, subtotal_minor BIGINT NOT NULL, tax_amount_minor BIGINT NOT NULL, total_minor BIGINT NOT NULL, position INT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, credit_note_id INT NOT NULL, invoice_line_id INT DEFAULT NULL, INDEX IDX_B0A453BC1C696F7A (credit_note_id), INDEX IDX_B0A453BCBFA24391 (invoice_line_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE devise (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) NOT NULL, signe VARCHAR(255) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE favoris (id INT AUTO_INCREMENT NOT NULL, created_at DATETIME DEFAULT NULL, user_id INT NOT NULL, property_id INT NOT NULL, INDEX IDX_8933C432A76ED395 (user_id), INDEX IDX_8933C432549213EC (property_id), UNIQUE INDEX UNIQ_FAVORIS_USER_PROPERTY (user_id, property_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE fuseau_horaire (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) NOT NULL, utc VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE horaire_ouverture (id INT AUTO_INCREMENT NOT NULL, is_open TINYINT DEFAULT 0 NOT NULL, jour VARCHAR(20) DEFAULT NULL, ouverture_matin TIME DEFAULT NULL, fermeture_matin TIME DEFAULT NULL, ouverture_apres_midi TIME DEFAULT NULL, fermeture_apres_midi TIME DEFAULT NULL, agence_id INT NOT NULL, INDEX IDX_D97D2495D725330D (agence_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE invoice (id INT AUTO_INCREMENT NOT NULL, number VARCHAR(100) NOT NULL, status VARCHAR(30) NOT NULL, type VARCHAR(30) NOT NULL, subtotal_minor BIGINT NOT NULL, discount_total_minor BIGINT NOT NULL, taxable_total_minor BIGINT NOT NULL, tax_total_minor BIGINT NOT NULL, total_minor BIGINT NOT NULL, amount_paid_minor BIGINT NOT NULL, amount_due_minor BIGINT NOT NULL, amount_refunded_minor BIGINT NOT NULL, seller_snapshot JSON NOT NULL, customer_snapshot JSON NOT NULL, tax_snapshot JSON NOT NULL, provider_invoice_id VARCHAR(255) DEFAULT NULL, provider_invoice_pdf_url LONGTEXT DEFAULT NULL, provider_hosted_invoice_url LONGTEXT DEFAULT NULL, issued_at DATETIME DEFAULT NULL, due_at DATETIME DEFAULT NULL, paid_at DATETIME DEFAULT NULL, voided_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, agency_id INT NOT NULL, billing_profile_id INT NOT NULL, subscription_id INT DEFAULT NULL, subscription_period_id INT DEFAULT NULL, payment_id INT DEFAULT NULL, currency_id INT NOT NULL, UNIQUE INDEX UNIQ_9065174496901F54 (number), UNIQUE INDEX UNIQ_90651744C3FBD45 (provider_invoice_id), INDEX IDX_90651744CDEADB2A (agency_id), INDEX IDX_90651744409D7D29 (billing_profile_id), INDEX IDX_906517449A1887DC (subscription_id), INDEX IDX_90651744DE34B862 (subscription_period_id), UNIQUE INDEX UNIQ_906517444C3A3BB (payment_id), INDEX IDX_9065174438248176 (currency_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE invoice_discount (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(100) DEFAULT NULL, description VARCHAR(255) NOT NULL, type VARCHAR(30) NOT NULL, percentage NUMERIC(8, 4) DEFAULT NULL, amount_minor BIGINT NOT NULL, provider_coupon_id VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, invoice_id INT NOT NULL, invoice_line_id INT DEFAULT NULL, INDEX IDX_FEC8EE562989F1FD (invoice_id), INDEX IDX_FEC8EE56BFA24391 (invoice_line_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE invoice_line (id INT AUTO_INCREMENT NOT NULL, type VARCHAR(50) NOT NULL, description VARCHAR(255) NOT NULL, quantity NUMERIC(12, 3) NOT NULL, unit_amount_minor BIGINT NOT NULL, subtotal_minor BIGINT NOT NULL, discount_amount_minor BIGINT NOT NULL, taxable_amount_minor BIGINT NOT NULL, tax_amount_minor BIGINT NOT NULL, total_minor BIGINT NOT NULL, period_start DATETIME DEFAULT NULL, period_end DATETIME DEFAULT NULL, position INT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, invoice_id INT NOT NULL, INDEX IDX_D3D1D6932989F1FD (invoice_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE invoice_tax (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL, type VARCHAR(50) NOT NULL, country_code VARCHAR(2) NOT NULL, region_code VARCHAR(50) DEFAULT NULL, rate NUMERIC(8, 5) NOT NULL, taxable_amount_minor BIGINT NOT NULL, amount_minor BIGINT NOT NULL, inclusive TINYINT NOT NULL, tax_behavior VARCHAR(30) NOT NULL, provider_tax_rate_id VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, invoice_id INT NOT NULL, invoice_line_id INT DEFAULT NULL, INDEX IDX_2670D5B52989F1FD (invoice_id), INDEX IDX_2670D5B5BFA24391 (invoice_line_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE langue_parler (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(10) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE langue_parler_user (langue_parler_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_8B8F5F4A89697D3E (langue_parler_id), INDEX IDX_8B8F5F4AA76ED395 (user_id), PRIMARY KEY (langue_parler_id, user_id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE langues (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, iso VARCHAR(10) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE maintenance_allowed_ip (id INT AUTO_INCREMENT NOT NULL, label VARCHAR(100) DEFAULT NULL, ip_address VARCHAR(45) NOT NULL, enabled TINYINT DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_CA6E11B122FFD58C (ip_address), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE maintenance_setting (id INT AUTO_INCREMENT NOT NULL, enabled TINYINT DEFAULT 0 NOT NULL, title VARCHAR(255) NOT NULL, message LONGTEXT NOT NULL, starts_at DATETIME DEFAULT NULL, ends_at DATETIME DEFAULT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE payment (id INT AUTO_INCREMENT NOT NULL, reference VARCHAR(100) NOT NULL, type VARCHAR(50) NOT NULL, status VARCHAR(40) NOT NULL, amount_subtotal_minor BIGINT NOT NULL, discount_amount_minor BIGINT NOT NULL, tax_amount_minor BIGINT NOT NULL, amount_total_minor BIGINT NOT NULL, amount_paid_minor BIGINT NOT NULL, amount_refunded_minor BIGINT NOT NULL, exchange_rate NUMERIC(18, 8) DEFAULT NULL, gross_settlement_amount_minor BIGINT NOT NULL, fee_settlement_amount_minor BIGINT NOT NULL, net_settlement_amount_minor BIGINT NOT NULL, provider VARCHAR(30) NOT NULL, provider_payment_intent_id VARCHAR(255) DEFAULT NULL, provider_charge_id VARCHAR(255) DEFAULT NULL, provider_invoice_id VARCHAR(255) DEFAULT NULL, provider_checkout_session_id VARCHAR(255) DEFAULT NULL, provider_balance_transaction_id VARCHAR(255) DEFAULT NULL, payment_method_snapshot JSON NOT NULL, metadata JSON NOT NULL, billing_period_start DATETIME DEFAULT NULL, billing_period_end DATETIME DEFAULT NULL, attempt_number INT DEFAULT NULL, failure_code VARCHAR(255) DEFAULT NULL, failure_message LONGTEXT DEFAULT NULL, authorized_at DATETIME DEFAULT NULL, paid_at DATETIME DEFAULT NULL, failed_at DATETIME DEFAULT NULL, canceled_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, agency_id INT NOT NULL, billing_profile_id INT NOT NULL, payment_method_id INT DEFAULT NULL, subscription_id INT DEFAULT NULL, booster_pack_id INT DEFAULT NULL, currency_id INT NOT NULL, settlement_currency_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_6D28840DAEA34913 (reference), UNIQUE INDEX UNIQ_6D28840DE8AB5F8C (provider_payment_intent_id), UNIQUE INDEX UNIQ_6D28840D8CB651A6 (provider_charge_id), UNIQUE INDEX UNIQ_6D28840DC3FBD45 (provider_invoice_id), UNIQUE INDEX UNIQ_6D28840D43276AFC (provider_checkout_session_id), INDEX IDX_6D28840DCDEADB2A (agency_id), INDEX IDX_6D28840D409D7D29 (billing_profile_id), INDEX IDX_6D28840D5AA1164F (payment_method_id), INDEX IDX_6D28840D9A1887DC (subscription_id), INDEX IDX_6D28840D32661930 (booster_pack_id), INDEX IDX_6D28840D38248176 (currency_id), INDEX IDX_6D28840D9978136E (settlement_currency_id), INDEX idx_payment_subscription_type (subscription_id, type), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE payment_attempt (id INT AUTO_INCREMENT NOT NULL, attempt_number INT NOT NULL, status VARCHAR(30) NOT NULL, provider_payment_intent_id VARCHAR(255) DEFAULT NULL, provider_invoice_id VARCHAR(255) DEFAULT NULL, provider_charge_id VARCHAR(255) DEFAULT NULL, amount_minor BIGINT NOT NULL, requires_action_type VARCHAR(100) DEFAULT NULL, decline_code VARCHAR(100) DEFAULT NULL, failure_code VARCHAR(100) DEFAULT NULL, failure_message LONGTEXT DEFAULT NULL, attempted_at DATETIME DEFAULT NULL, completed_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, payment_id INT NOT NULL, subscription_id INT DEFAULT NULL, payment_method_id INT DEFAULT NULL, currency_id INT NOT NULL, INDEX IDX_1A50C8C4C3A3BB (payment_id), INDEX IDX_1A50C8C9A1887DC (subscription_id), INDEX IDX_1A50C8C5AA1164F (payment_method_id), INDEX IDX_1A50C8C38248176 (currency_id), INDEX idx_payment_attempt_subscription_invoice (subscription_id, provider_invoice_id), UNIQUE INDEX uniq_payment_attempt_invoice_number (subscription_id, provider_invoice_id, attempt_number), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE payment_fee (id INT AUTO_INCREMENT NOT NULL, type VARCHAR(60) NOT NULL, amount_minor BIGINT NOT NULL, provider_balance_transaction_id VARCHAR(255) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, is_refundable TINYINT DEFAULT 0 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, payment_id INT NOT NULL, refund_id INT DEFAULT NULL, currency_id INT NOT NULL, INDEX IDX_A12AA5814C3A3BB (payment_id), INDEX IDX_A12AA581189801D5 (refund_id), INDEX IDX_A12AA58138248176 (currency_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE payment_webhook_event (id INT AUTO_INCREMENT NOT NULL, provider VARCHAR(30) NOT NULL, provider_event_id VARCHAR(255) NOT NULL, event_type VARCHAR(150) NOT NULL, api_version VARCHAR(50) DEFAULT NULL, livemode TINYINT NOT NULL, payload JSON NOT NULL, status VARCHAR(30) NOT NULL, attempt_count INT NOT NULL, received_at DATETIME NOT NULL, processed_at DATETIME DEFAULT NULL, failed_at DATETIME DEFAULT NULL, error_message LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_4C7AE61339B58662 (provider_event_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pays (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) NOT NULL, iso VARCHAR(5) NOT NULL, devise_id INT DEFAULT NULL, INDEX IDX_349F3CAEF4445056 (devise_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE property (id INT AUTO_INCREMENT NOT NULL, code_postal VARCHAR(255) DEFAULT NULL, latitude NUMERIC(10, 7) DEFAULT NULL, longitude NUMERIC(10, 7) DEFAULT NULL, mapbox_id VARCHAR(255) DEFAULT NULL, feature_type VARCHAR(255) DEFAULT NULL, annee_construction VARCHAR(255) DEFAULT NULL, chambres VARCHAR(255) DEFAULT NULL, salle_de_bains VARCHAR(255) DEFAULT NULL, surface_total VARCHAR(255) DEFAULT NULL, dpe VARCHAR(255) DEFAULT NULL, dpe_lettre VARCHAR(255) DEFAULT NULL, ges VARCHAR(255) DEFAULT NULL, ges_lettre VARCHAR(255) DEFAULT NULL, dpe_min VARCHAR(255) DEFAULT NULL, dpe_max VARCHAR(255) DEFAULT NULL, date_indexation_energie DATETIME DEFAULT NULL, prix VARCHAR(255) DEFAULT NULL, reference_interne VARCHAR(255) DEFAULT NULL, montant_loyer_hors_charge VARCHAR(255) DEFAULT NULL, montant_depot_de_garantie VARCHAR(255) DEFAULT NULL, montant_des_charges VARCHAR(255) DEFAULT NULL, statut VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, session_id_mapbox VARCHAR(255) DEFAULT NULL, show_adresse TINYINT DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, type_bien_id INT DEFAULT NULL, type_transaction_id INT DEFAULT NULL, user_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_8BF21CDE989D9B62 (slug), INDEX IDX_8BF21CDE95B4D7FA (type_bien_id), INDEX IDX_8BF21CDE7903E29B (type_transaction_id), INDEX IDX_8BF21CDEA76ED395 (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE property_caracteristique (property_id INT NOT NULL, caracteristique_id INT NOT NULL, INDEX IDX_D6F4BE49549213EC (property_id), INDEX IDX_D6F4BE491704EEB7 (caracteristique_id), PRIMARY KEY (property_id, caracteristique_id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE property_boost (id INT AUTO_INCREMENT NOT NULL, status VARCHAR(20) NOT NULL, starts_at DATETIME NOT NULL, ends_at DATETIME NOT NULL, canceled_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, property_id INT NOT NULL, agency_id INT NOT NULL, booster_transaction_id INT NOT NULL, INDEX IDX_9077E665549213EC (property_id), INDEX IDX_9077E665CDEADB2A (agency_id), UNIQUE INDEX UNIQ_9077E6655AB07211 (booster_transaction_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE property_image (id INT AUTO_INCREMENT NOT NULL, image_name VARCHAR(255) DEFAULT NULL, image_size INT DEFAULT NULL, position VARCHAR(255) NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, property_id INT NOT NULL, INDEX IDX_32EC552549213EC (property_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE property_search_session (id BIGINT AUTO_INCREMENT NOT NULL, uuid BINARY(16) NOT NULL, transaction_type_id BIGINT NOT NULL, ville VARCHAR(180) DEFAULT NULL, cp VARCHAR(50) DEFAULT NULL, pays VARCHAR(180) NOT NULL, filters JSON DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, expires_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_8B51E14AD17F50A6 (uuid), INDEX idx_property_search_session_uuid (uuid), INDEX idx_property_search_session_transaction_type (transaction_type_id), INDEX idx_property_search_session_ville (ville), INDEX idx_property_search_session_cp (cp), INDEX idx_property_search_session_pays (pays), INDEX idx_property_search_session_expires_at (expires_at), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE property_translation (id INT AUTO_INCREMENT NOT NULL, adresse VARCHAR(255) DEFAULT NULL, ville VARCHAR(255) DEFAULT NULL, pays VARCHAR(255) DEFAULT NULL, full_address VARCHAR(255) DEFAULT NULL, region VARCHAR(255) DEFAULT NULL, district VARCHAR(255) DEFAULT NULL, locality VARCHAR(255) DEFAULT NULL, neighborhood VARCHAR(255) DEFAULT NULL, poi VARCHAR(255) DEFAULT NULL, titre_du_logement VARCHAR(255) DEFAULT NULL, description_logement LONGTEXT DEFAULT NULL, locale VARCHAR(5) NOT NULL, translatable_id INT DEFAULT NULL, INDEX IDX_B0C85592C2AC5D3 (translatable_id), UNIQUE INDEX property_translation_unique_translation (translatable_id, locale), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE property_view (id INT AUTO_INCREMENT NOT NULL, view_key VARCHAR(64) NOT NULL, visitor_hash VARCHAR(64) NOT NULL, viewed_at DATETIME NOT NULL, property_id INT NOT NULL, user_id INT DEFAULT NULL, INDEX idx_property_view_property (property_id), INDEX idx_property_view_user (user_id), INDEX idx_property_view_viewed_at (viewed_at), INDEX idx_property_view_property_date (property_id, viewed_at), UNIQUE INDEX uniq_property_view_key (view_key), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE refund (id INT AUTO_INCREMENT NOT NULL, reference VARCHAR(100) NOT NULL, status VARCHAR(30) NOT NULL, reason VARCHAR(50) NOT NULL, amount_minor BIGINT NOT NULL, provider_refund_id VARCHAR(255) DEFAULT NULL, provider_balance_transaction_id VARCHAR(255) DEFAULT NULL, failure_reason VARCHAR(255) DEFAULT NULL, metadata JSON NOT NULL, requested_at DATETIME NOT NULL, processed_at DATETIME DEFAULT NULL, failed_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, payment_id INT NOT NULL, invoice_id INT DEFAULT NULL, currency_id INT NOT NULL, UNIQUE INDEX UNIQ_5B2C1458AEA34913 (reference), UNIQUE INDEX UNIQ_5B2C1458C1061967 (provider_refund_id), INDEX IDX_5B2C14584C3A3BB (payment_id), INDEX IDX_5B2C14582989F1FD (invoice_id), INDEX IDX_5B2C145838248176 (currency_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE required_document (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(150) NOT NULL, description LONGTEXT DEFAULT NULL, required TINYINT NOT NULL, enabled TINYINT NOT NULL, max_submissions INT NOT NULL, position INT NOT NULL, accepted_mime_types VARCHAR(255) DEFAULT NULL, max_file_size_mb INT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE reset_password_request (id INT AUTO_INCREMENT NOT NULL, selector VARCHAR(20) NOT NULL, hashed_token VARCHAR(100) NOT NULL, requested_at DATETIME NOT NULL, expires_at DATETIME NOT NULL, user_id INT NOT NULL, INDEX IDX_7CE748AA76ED395 (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE subscription_email_log (id INT AUTO_INCREMENT NOT NULL, event_type VARCHAR(80) NOT NULL, event_key VARCHAR(255) NOT NULL, recipient_email VARCHAR(255) NOT NULL, subject VARCHAR(255) NOT NULL, context JSON NOT NULL, status VARCHAR(30) NOT NULL, queued_at DATETIME NOT NULL, sent_at DATETIME DEFAULT NULL, failed_at DATETIME DEFAULT NULL, error_message LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, subscription_id INT NOT NULL, agency_id INT NOT NULL, INDEX IDX_34448A3F9A1887DC (subscription_id), INDEX IDX_34448A3FCDEADB2A (agency_id), UNIQUE INDEX uniq_subscription_email_event (subscription_id, event_type, event_key), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE subscription_history (id INT AUTO_INCREMENT NOT NULL, event_type VARCHAR(80) NOT NULL, old_status VARCHAR(30) DEFAULT NULL, new_status VARCHAR(30) DEFAULT NULL, old_plan VARCHAR(80) DEFAULT NULL, new_plan VARCHAR(80) DEFAULT NULL, provider_invoice_id VARCHAR(255) DEFAULT NULL, provider_payment_intent_id VARCHAR(255) DEFAULT NULL, metadata JSON NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, subscription_id INT NOT NULL, agency_id INT NOT NULL, INDEX IDX_54AF90D09A1887DC (subscription_id), INDEX IDX_54AF90D0CDEADB2A (agency_id), INDEX idx_subscription_history_subscription_event (subscription_id, event_type), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE subscription_plan (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(150) NOT NULL, description LONGTEXT DEFAULT NULL, property_limit INT DEFAULT NULL, included_boosts INT DEFAULT 0 NOT NULL, boost_duration_days INT DEFAULT 7 NOT NULL, is_free TINYINT DEFAULT 0 NOT NULL, is_default TINYINT DEFAULT 0 NOT NULL, is_active TINYINT DEFAULT 1 NOT NULL, position INT DEFAULT 0 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX uniq_subscription_plan_code (code), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE subscription_plan_price (id INT AUTO_INCREMENT NOT NULL, amount_minor BIGINT NOT NULL, billing_period VARCHAR(10) NOT NULL, payment_provider_price_id VARCHAR(255) DEFAULT NULL, is_active TINYINT DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, plan_id INT NOT NULL, currency_id INT NOT NULL, UNIQUE INDEX UNIQ_5B8B2740B2C0EFFF (payment_provider_price_id), INDEX IDX_5B8B2740E899029B (plan_id), INDEX IDX_5B8B274038248176 (currency_id), UNIQUE INDEX uniq_subscription_plan_currency_period (plan_id, currency_id, billing_period), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE translation (id INT AUTO_INCREMENT NOT NULL, `key` VARCHAR(255) NOT NULL, locale VARCHAR(255) NOT NULL, translation LONGTEXT NOT NULL, page VARCHAR(255) NOT NULL, UNIQUE INDEX uniq_translation_key_locale (`key`, locale), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE user_document_request (id INT AUTO_INCREMENT NOT NULL, status VARCHAR(255) DEFAULT \'waiting_upload\' NOT NULL, blocked TINYINT NOT NULL, blocked_reason VARCHAR(500) DEFAULT NULL, blocked_at DATETIME DEFAULT NULL, completed_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, user_id INT NOT NULL, required_document_id INT NOT NULL, INDEX IDX_E2ED6B9EA76ED395 (user_id), INDEX IDX_E2ED6B9E837C14A7 (required_document_id), UNIQUE INDEX uniq_user_required_document (user_id, required_document_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE user_document_submission (id INT AUTO_INCREMENT NOT NULL, file_name VARCHAR(255) NOT NULL, original_file_name VARCHAR(255) NOT NULL, mime_type VARCHAR(150) NOT NULL, file_size INT NOT NULL, storage_path VARCHAR(500) NOT NULL, checksum VARCHAR(64) NOT NULL, attempt_number INT NOT NULL, status VARCHAR(255) DEFAULT \'pending\' NOT NULL, rejection_reason LONGTEXT DEFAULT NULL, reviewed_at DATETIME DEFAULT NULL, submitted_at DATETIME NOT NULL, document_request_id INT NOT NULL, reviewed_by_id INT DEFAULT NULL, INDEX IDX_50059ED7E3BD13F3 (document_request_id), INDEX IDX_50059ED7FC6B21F1 (reviewed_by_id), UNIQUE INDEX uniq_document_attempt (document_request_id, attempt_number), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE user_translation (id INT AUTO_INCREMENT NOT NULL, adresse VARCHAR(255) DEFAULT NULL, adresse_complement VARCHAR(255) DEFAULT NULL, ville VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, adresse_contact VARCHAR(255) DEFAULT NULL, ville_contact VARCHAR(255) DEFAULT NULL, pays_contact VARCHAR(255) DEFAULT NULL, adresse_complement_contact VARCHAR(255) DEFAULT NULL, locale VARCHAR(5) NOT NULL, translatable_id INT DEFAULT NULL, INDEX IDX_1D728CFA2C2AC5D3 (translatable_id), UNIQUE INDEX user_translation_unique_translation (translatable_id, locale), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE `utilisateur` (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(250) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) DEFAULT NULL, is_verified TINYINT NOT NULL, email_auth_code VARCHAR(255) DEFAULT NULL, email_auth_code_expires_at DATETIME DEFAULT NULL, email_auth_code_requested_at DATETIME DEFAULT NULL, failed_verification_attempts INT DEFAULT 0 NOT NULL, agency_registration_step VARCHAR(20) DEFAULT NULL, email_auth_enabled TINYINT DEFAULT 0 NOT NULL, nom VARCHAR(255) DEFAULT NULL, prenom VARCHAR(255) DEFAULT NULL, telephone VARCHAR(20) DEFAULT NULL, image_name VARCHAR(255) DEFAULT NULL, image_size INT DEFAULT NULL, code_postal VARCHAR(255) DEFAULT NULL, entreprise VARCHAR(255) DEFAULT NULL, email_contact VARCHAR(255) DEFAULT NULL, numero_contact VARCHAR(255) DEFAULT NULL, code_postal_contact VARCHAR(255) DEFAULT NULL, whats_app VARCHAR(255) DEFAULT NULL, slug VARCHAR(255) DEFAULT NULL, visit_agency INT DEFAULT 0 NOT NULL, document_deletion_warning_thirty_days_sent_at DATETIME DEFAULT NULL, document_deletion_warning_fifteen_days_sent_at DATETIME DEFAULT NULL, document_deletion_warning_five_days_sent_at DATETIME DEFAULT NULL, created_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, last_login_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, pays_id INT DEFAULT NULL, langues_id INT DEFAULT NULL, devise_id INT DEFAULT NULL, fuseau_horaire_id INT DEFAULT NULL, INDEX IDX_1D1C63B3A6E44244 (pays_id), INDEX IDX_1D1C63B328EAE92 (langues_id), INDEX IDX_1D1C63B3F4445056 (devise_id), INDEX IDX_1D1C63B398DBDF9B (fuseau_horaire_id), INDEX IDX_USER_VERIFIED (is_verified), UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL (email), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL, available_at DATETIME NOT NULL, delivered_at DATETIME DEFAULT NULL, INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 (queue_name, available_at, delivered_at, id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('ALTER TABLE agency_billing_profile ADD CONSTRAINT FK_7F37F400CDEADB2A FOREIGN KEY (agency_id) REFERENCES `utilisateur` (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE agency_billing_profile ADD CONSTRAINT FK_7F37F4007A5B1307 FOREIGN KEY (preferred_currency_id) REFERENCES devise (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE agency_billing_profile ADD CONSTRAINT FK_7F37F400AF212FD0 FOREIGN KEY (default_payment_method_id) REFERENCES agency_payment_method (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE agency_notification ADD CONSTRAINT FK_30AE0EFCDEADB2A FOREIGN KEY (agency_id) REFERENCES `utilisateur` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE agency_payment_method ADD CONSTRAINT FK_8AFEFB3E409D7D29 FOREIGN KEY (billing_profile_id) REFERENCES agency_billing_profile (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE agency_profile_daily_visit ADD CONSTRAINT FK_507FAD7ECDEADB2A FOREIGN KEY (agency_id) REFERENCES `utilisateur` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE agency_subscription ADD CONSTRAINT FK_1F98F2F6CDEADB2A FOREIGN KEY (agency_id) REFERENCES `utilisateur` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE agency_subscription ADD CONSTRAINT FK_1F98F2F6E899029B FOREIGN KEY (plan_id) REFERENCES subscription_plan (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE agency_subscription ADD CONSTRAINT FK_1F98F2F6D871F09D FOREIGN KEY (plan_price_id) REFERENCES subscription_plan_price (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE agency_subscription ADD CONSTRAINT FK_1F98F2F6AE027C2 FOREIGN KEY (pending_plan_price_id) REFERENCES subscription_plan_price (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE agency_subscription ADD CONSTRAINT FK_1F98F2F6CAD137FF FOREIGN KEY (currency_snapshot_id) REFERENCES devise (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE agency_subscription_period ADD CONSTRAINT FK_8A7365A49A1887DC FOREIGN KEY (subscription_id) REFERENCES agency_subscription (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE agency_subscription_period ADD CONSTRAINT FK_8A7365A438248176 FOREIGN KEY (currency_id) REFERENCES devise (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE agency_subscription_period ADD CONSTRAINT FK_8A7365A44C3A3BB FOREIGN KEY (payment_id) REFERENCES payment (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE billing_tax_identifier ADD CONSTRAINT FK_247C4B01409D7D29 FOREIGN KEY (billing_profile_id) REFERENCES agency_billing_profile (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE booster_pack_price ADD CONSTRAINT FK_C877F16932661930 FOREIGN KEY (booster_pack_id) REFERENCES booster_pack (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE booster_pack_price ADD CONSTRAINT FK_C877F16938248176 FOREIGN KEY (currency_id) REFERENCES devise (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE booster_transaction ADD CONSTRAINT FK_9EE4BCAECDEADB2A FOREIGN KEY (agency_id) REFERENCES `utilisateur` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE booster_transaction ADD CONSTRAINT FK_9EE4BCAE549213EC FOREIGN KEY (property_id) REFERENCES property (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE booster_transaction ADD CONSTRAINT FK_9EE4BCAE32661930 FOREIGN KEY (booster_pack_id) REFERENCES booster_pack (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE booster_transaction ADD CONSTRAINT FK_9EE4BCAEDE34B862 FOREIGN KEY (subscription_period_id) REFERENCES agency_subscription_period (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE booster_transaction ADD CONSTRAINT FK_9EE4BCAE4C3A3BB FOREIGN KEY (payment_id) REFERENCES payment (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE caracteristique_translation ADD CONSTRAINT FK_9AB160AD2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES caracteristique (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE category_bien_transaction_translation ADD CONSTRAINT FK_96E036FE2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES category_bien_transaction (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE category_bien_translation ADD CONSTRAINT FK_8E410EED2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES category_bien (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE contact ADD CONSTRAINT FK_4C62E638D725330D FOREIGN KEY (agence_id) REFERENCES `utilisateur` (id)');
        $this->addSql('ALTER TABLE credit_note ADD CONSTRAINT FK_C87F45292989F1FD FOREIGN KEY (invoice_id) REFERENCES invoice (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE credit_note ADD CONSTRAINT FK_C87F4529189801D5 FOREIGN KEY (refund_id) REFERENCES refund (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE credit_note ADD CONSTRAINT FK_C87F452938248176 FOREIGN KEY (currency_id) REFERENCES devise (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE credit_note_line ADD CONSTRAINT FK_B0A453BC1C696F7A FOREIGN KEY (credit_note_id) REFERENCES credit_note (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE credit_note_line ADD CONSTRAINT FK_B0A453BCBFA24391 FOREIGN KEY (invoice_line_id) REFERENCES invoice_line (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE favoris ADD CONSTRAINT FK_8933C432A76ED395 FOREIGN KEY (user_id) REFERENCES `utilisateur` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE favoris ADD CONSTRAINT FK_8933C432549213EC FOREIGN KEY (property_id) REFERENCES property (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE horaire_ouverture ADD CONSTRAINT FK_D97D2495D725330D FOREIGN KEY (agence_id) REFERENCES `utilisateur` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE invoice ADD CONSTRAINT FK_90651744CDEADB2A FOREIGN KEY (agency_id) REFERENCES `utilisateur` (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE invoice ADD CONSTRAINT FK_90651744409D7D29 FOREIGN KEY (billing_profile_id) REFERENCES agency_billing_profile (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE invoice ADD CONSTRAINT FK_906517449A1887DC FOREIGN KEY (subscription_id) REFERENCES agency_subscription (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE invoice ADD CONSTRAINT FK_90651744DE34B862 FOREIGN KEY (subscription_period_id) REFERENCES agency_subscription_period (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE invoice ADD CONSTRAINT FK_906517444C3A3BB FOREIGN KEY (payment_id) REFERENCES payment (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE invoice ADD CONSTRAINT FK_9065174438248176 FOREIGN KEY (currency_id) REFERENCES devise (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE invoice_discount ADD CONSTRAINT FK_FEC8EE562989F1FD FOREIGN KEY (invoice_id) REFERENCES invoice (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE invoice_discount ADD CONSTRAINT FK_FEC8EE56BFA24391 FOREIGN KEY (invoice_line_id) REFERENCES invoice_line (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE invoice_line ADD CONSTRAINT FK_D3D1D6932989F1FD FOREIGN KEY (invoice_id) REFERENCES invoice (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE invoice_tax ADD CONSTRAINT FK_2670D5B52989F1FD FOREIGN KEY (invoice_id) REFERENCES invoice (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE invoice_tax ADD CONSTRAINT FK_2670D5B5BFA24391 FOREIGN KEY (invoice_line_id) REFERENCES invoice_line (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE langue_parler_user ADD CONSTRAINT FK_8B8F5F4A89697D3E FOREIGN KEY (langue_parler_id) REFERENCES langue_parler (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE langue_parler_user ADD CONSTRAINT FK_8B8F5F4AA76ED395 FOREIGN KEY (user_id) REFERENCES `utilisateur` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840DCDEADB2A FOREIGN KEY (agency_id) REFERENCES `utilisateur` (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840D409D7D29 FOREIGN KEY (billing_profile_id) REFERENCES agency_billing_profile (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840D5AA1164F FOREIGN KEY (payment_method_id) REFERENCES agency_payment_method (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840D9A1887DC FOREIGN KEY (subscription_id) REFERENCES agency_subscription (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840D32661930 FOREIGN KEY (booster_pack_id) REFERENCES booster_pack (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840D38248176 FOREIGN KEY (currency_id) REFERENCES devise (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840D9978136E FOREIGN KEY (settlement_currency_id) REFERENCES devise (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE payment_attempt ADD CONSTRAINT FK_1A50C8C4C3A3BB FOREIGN KEY (payment_id) REFERENCES payment (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE payment_attempt ADD CONSTRAINT FK_1A50C8C9A1887DC FOREIGN KEY (subscription_id) REFERENCES agency_subscription (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE payment_attempt ADD CONSTRAINT FK_1A50C8C5AA1164F FOREIGN KEY (payment_method_id) REFERENCES agency_payment_method (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE payment_attempt ADD CONSTRAINT FK_1A50C8C38248176 FOREIGN KEY (currency_id) REFERENCES devise (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE payment_fee ADD CONSTRAINT FK_A12AA5814C3A3BB FOREIGN KEY (payment_id) REFERENCES payment (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE payment_fee ADD CONSTRAINT FK_A12AA581189801D5 FOREIGN KEY (refund_id) REFERENCES refund (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE payment_fee ADD CONSTRAINT FK_A12AA58138248176 FOREIGN KEY (currency_id) REFERENCES devise (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE pays ADD CONSTRAINT FK_349F3CAEF4445056 FOREIGN KEY (devise_id) REFERENCES devise (id)');
        $this->addSql('ALTER TABLE property ADD CONSTRAINT FK_8BF21CDE95B4D7FA FOREIGN KEY (type_bien_id) REFERENCES category_bien (id)');
        $this->addSql('ALTER TABLE property ADD CONSTRAINT FK_8BF21CDE7903E29B FOREIGN KEY (type_transaction_id) REFERENCES category_bien_transaction (id)');
        $this->addSql('ALTER TABLE property ADD CONSTRAINT FK_8BF21CDEA76ED395 FOREIGN KEY (user_id) REFERENCES `utilisateur` (id)');
        $this->addSql('ALTER TABLE property_caracteristique ADD CONSTRAINT FK_D6F4BE49549213EC FOREIGN KEY (property_id) REFERENCES property (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE property_caracteristique ADD CONSTRAINT FK_D6F4BE491704EEB7 FOREIGN KEY (caracteristique_id) REFERENCES caracteristique (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE property_boost ADD CONSTRAINT FK_9077E665549213EC FOREIGN KEY (property_id) REFERENCES property (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE property_boost ADD CONSTRAINT FK_9077E665CDEADB2A FOREIGN KEY (agency_id) REFERENCES `utilisateur` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE property_boost ADD CONSTRAINT FK_9077E6655AB07211 FOREIGN KEY (booster_transaction_id) REFERENCES booster_transaction (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE property_image ADD CONSTRAINT FK_32EC552549213EC FOREIGN KEY (property_id) REFERENCES property (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE property_translation ADD CONSTRAINT FK_B0C85592C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES property (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE property_view ADD CONSTRAINT FK_E1E514B4549213EC FOREIGN KEY (property_id) REFERENCES property (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE property_view ADD CONSTRAINT FK_E1E514B4A76ED395 FOREIGN KEY (user_id) REFERENCES `utilisateur` (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE refund ADD CONSTRAINT FK_5B2C14584C3A3BB FOREIGN KEY (payment_id) REFERENCES payment (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE refund ADD CONSTRAINT FK_5B2C14582989F1FD FOREIGN KEY (invoice_id) REFERENCES invoice (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE refund ADD CONSTRAINT FK_5B2C145838248176 FOREIGN KEY (currency_id) REFERENCES devise (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE reset_password_request ADD CONSTRAINT FK_7CE748AA76ED395 FOREIGN KEY (user_id) REFERENCES `utilisateur` (id)');
        $this->addSql('ALTER TABLE subscription_email_log ADD CONSTRAINT FK_34448A3F9A1887DC FOREIGN KEY (subscription_id) REFERENCES agency_subscription (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE subscription_email_log ADD CONSTRAINT FK_34448A3FCDEADB2A FOREIGN KEY (agency_id) REFERENCES `utilisateur` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE subscription_history ADD CONSTRAINT FK_54AF90D09A1887DC FOREIGN KEY (subscription_id) REFERENCES agency_subscription (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE subscription_history ADD CONSTRAINT FK_54AF90D0CDEADB2A FOREIGN KEY (agency_id) REFERENCES `utilisateur` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE subscription_plan_price ADD CONSTRAINT FK_5B8B2740E899029B FOREIGN KEY (plan_id) REFERENCES subscription_plan (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE subscription_plan_price ADD CONSTRAINT FK_5B8B274038248176 FOREIGN KEY (currency_id) REFERENCES devise (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE user_document_request ADD CONSTRAINT FK_E2ED6B9EA76ED395 FOREIGN KEY (user_id) REFERENCES `utilisateur` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_document_request ADD CONSTRAINT FK_E2ED6B9E837C14A7 FOREIGN KEY (required_document_id) REFERENCES required_document (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE user_document_submission ADD CONSTRAINT FK_50059ED7E3BD13F3 FOREIGN KEY (document_request_id) REFERENCES user_document_request (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_document_submission ADD CONSTRAINT FK_50059ED7FC6B21F1 FOREIGN KEY (reviewed_by_id) REFERENCES `utilisateur` (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE user_translation ADD CONSTRAINT FK_1D728CFA2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES `utilisateur` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE `utilisateur` ADD CONSTRAINT FK_1D1C63B3A6E44244 FOREIGN KEY (pays_id) REFERENCES pays (id)');
        $this->addSql('ALTER TABLE `utilisateur` ADD CONSTRAINT FK_1D1C63B328EAE92 FOREIGN KEY (langues_id) REFERENCES langues (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE `utilisateur` ADD CONSTRAINT FK_1D1C63B3F4445056 FOREIGN KEY (devise_id) REFERENCES devise (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE `utilisateur` ADD CONSTRAINT FK_1D1C63B398DBDF9B FOREIGN KEY (fuseau_horaire_id) REFERENCES fuseau_horaire (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE agency_billing_profile DROP FOREIGN KEY FK_7F37F400CDEADB2A');
        $this->addSql('ALTER TABLE agency_billing_profile DROP FOREIGN KEY FK_7F37F4007A5B1307');
        $this->addSql('ALTER TABLE agency_billing_profile DROP FOREIGN KEY FK_7F37F400AF212FD0');
        $this->addSql('ALTER TABLE agency_notification DROP FOREIGN KEY FK_30AE0EFCDEADB2A');
        $this->addSql('ALTER TABLE agency_payment_method DROP FOREIGN KEY FK_8AFEFB3E409D7D29');
        $this->addSql('ALTER TABLE agency_profile_daily_visit DROP FOREIGN KEY FK_507FAD7ECDEADB2A');
        $this->addSql('ALTER TABLE agency_subscription DROP FOREIGN KEY FK_1F98F2F6CDEADB2A');
        $this->addSql('ALTER TABLE agency_subscription DROP FOREIGN KEY FK_1F98F2F6E899029B');
        $this->addSql('ALTER TABLE agency_subscription DROP FOREIGN KEY FK_1F98F2F6D871F09D');
        $this->addSql('ALTER TABLE agency_subscription DROP FOREIGN KEY FK_1F98F2F6AE027C2');
        $this->addSql('ALTER TABLE agency_subscription DROP FOREIGN KEY FK_1F98F2F6CAD137FF');
        $this->addSql('ALTER TABLE agency_subscription_period DROP FOREIGN KEY FK_8A7365A49A1887DC');
        $this->addSql('ALTER TABLE agency_subscription_period DROP FOREIGN KEY FK_8A7365A438248176');
        $this->addSql('ALTER TABLE agency_subscription_period DROP FOREIGN KEY FK_8A7365A44C3A3BB');
        $this->addSql('ALTER TABLE billing_tax_identifier DROP FOREIGN KEY FK_247C4B01409D7D29');
        $this->addSql('ALTER TABLE booster_pack_price DROP FOREIGN KEY FK_C877F16932661930');
        $this->addSql('ALTER TABLE booster_pack_price DROP FOREIGN KEY FK_C877F16938248176');
        $this->addSql('ALTER TABLE booster_transaction DROP FOREIGN KEY FK_9EE4BCAECDEADB2A');
        $this->addSql('ALTER TABLE booster_transaction DROP FOREIGN KEY FK_9EE4BCAE549213EC');
        $this->addSql('ALTER TABLE booster_transaction DROP FOREIGN KEY FK_9EE4BCAE32661930');
        $this->addSql('ALTER TABLE booster_transaction DROP FOREIGN KEY FK_9EE4BCAEDE34B862');
        $this->addSql('ALTER TABLE booster_transaction DROP FOREIGN KEY FK_9EE4BCAE4C3A3BB');
        $this->addSql('ALTER TABLE caracteristique_translation DROP FOREIGN KEY FK_9AB160AD2C2AC5D3');
        $this->addSql('ALTER TABLE category_bien_transaction_translation DROP FOREIGN KEY FK_96E036FE2C2AC5D3');
        $this->addSql('ALTER TABLE category_bien_translation DROP FOREIGN KEY FK_8E410EED2C2AC5D3');
        $this->addSql('ALTER TABLE contact DROP FOREIGN KEY FK_4C62E638D725330D');
        $this->addSql('ALTER TABLE credit_note DROP FOREIGN KEY FK_C87F45292989F1FD');
        $this->addSql('ALTER TABLE credit_note DROP FOREIGN KEY FK_C87F4529189801D5');
        $this->addSql('ALTER TABLE credit_note DROP FOREIGN KEY FK_C87F452938248176');
        $this->addSql('ALTER TABLE credit_note_line DROP FOREIGN KEY FK_B0A453BC1C696F7A');
        $this->addSql('ALTER TABLE credit_note_line DROP FOREIGN KEY FK_B0A453BCBFA24391');
        $this->addSql('ALTER TABLE favoris DROP FOREIGN KEY FK_8933C432A76ED395');
        $this->addSql('ALTER TABLE favoris DROP FOREIGN KEY FK_8933C432549213EC');
        $this->addSql('ALTER TABLE horaire_ouverture DROP FOREIGN KEY FK_D97D2495D725330D');
        $this->addSql('ALTER TABLE invoice DROP FOREIGN KEY FK_90651744CDEADB2A');
        $this->addSql('ALTER TABLE invoice DROP FOREIGN KEY FK_90651744409D7D29');
        $this->addSql('ALTER TABLE invoice DROP FOREIGN KEY FK_906517449A1887DC');
        $this->addSql('ALTER TABLE invoice DROP FOREIGN KEY FK_90651744DE34B862');
        $this->addSql('ALTER TABLE invoice DROP FOREIGN KEY FK_906517444C3A3BB');
        $this->addSql('ALTER TABLE invoice DROP FOREIGN KEY FK_9065174438248176');
        $this->addSql('ALTER TABLE invoice_discount DROP FOREIGN KEY FK_FEC8EE562989F1FD');
        $this->addSql('ALTER TABLE invoice_discount DROP FOREIGN KEY FK_FEC8EE56BFA24391');
        $this->addSql('ALTER TABLE invoice_line DROP FOREIGN KEY FK_D3D1D6932989F1FD');
        $this->addSql('ALTER TABLE invoice_tax DROP FOREIGN KEY FK_2670D5B52989F1FD');
        $this->addSql('ALTER TABLE invoice_tax DROP FOREIGN KEY FK_2670D5B5BFA24391');
        $this->addSql('ALTER TABLE langue_parler_user DROP FOREIGN KEY FK_8B8F5F4A89697D3E');
        $this->addSql('ALTER TABLE langue_parler_user DROP FOREIGN KEY FK_8B8F5F4AA76ED395');
        $this->addSql('ALTER TABLE payment DROP FOREIGN KEY FK_6D28840DCDEADB2A');
        $this->addSql('ALTER TABLE payment DROP FOREIGN KEY FK_6D28840D409D7D29');
        $this->addSql('ALTER TABLE payment DROP FOREIGN KEY FK_6D28840D5AA1164F');
        $this->addSql('ALTER TABLE payment DROP FOREIGN KEY FK_6D28840D9A1887DC');
        $this->addSql('ALTER TABLE payment DROP FOREIGN KEY FK_6D28840D32661930');
        $this->addSql('ALTER TABLE payment DROP FOREIGN KEY FK_6D28840D38248176');
        $this->addSql('ALTER TABLE payment DROP FOREIGN KEY FK_6D28840D9978136E');
        $this->addSql('ALTER TABLE payment_attempt DROP FOREIGN KEY FK_1A50C8C4C3A3BB');
        $this->addSql('ALTER TABLE payment_attempt DROP FOREIGN KEY FK_1A50C8C9A1887DC');
        $this->addSql('ALTER TABLE payment_attempt DROP FOREIGN KEY FK_1A50C8C5AA1164F');
        $this->addSql('ALTER TABLE payment_attempt DROP FOREIGN KEY FK_1A50C8C38248176');
        $this->addSql('ALTER TABLE payment_fee DROP FOREIGN KEY FK_A12AA5814C3A3BB');
        $this->addSql('ALTER TABLE payment_fee DROP FOREIGN KEY FK_A12AA581189801D5');
        $this->addSql('ALTER TABLE payment_fee DROP FOREIGN KEY FK_A12AA58138248176');
        $this->addSql('ALTER TABLE pays DROP FOREIGN KEY FK_349F3CAEF4445056');
        $this->addSql('ALTER TABLE property DROP FOREIGN KEY FK_8BF21CDE95B4D7FA');
        $this->addSql('ALTER TABLE property DROP FOREIGN KEY FK_8BF21CDE7903E29B');
        $this->addSql('ALTER TABLE property DROP FOREIGN KEY FK_8BF21CDEA76ED395');
        $this->addSql('ALTER TABLE property_caracteristique DROP FOREIGN KEY FK_D6F4BE49549213EC');
        $this->addSql('ALTER TABLE property_caracteristique DROP FOREIGN KEY FK_D6F4BE491704EEB7');
        $this->addSql('ALTER TABLE property_boost DROP FOREIGN KEY FK_9077E665549213EC');
        $this->addSql('ALTER TABLE property_boost DROP FOREIGN KEY FK_9077E665CDEADB2A');
        $this->addSql('ALTER TABLE property_boost DROP FOREIGN KEY FK_9077E6655AB07211');
        $this->addSql('ALTER TABLE property_image DROP FOREIGN KEY FK_32EC552549213EC');
        $this->addSql('ALTER TABLE property_translation DROP FOREIGN KEY FK_B0C85592C2AC5D3');
        $this->addSql('ALTER TABLE property_view DROP FOREIGN KEY FK_E1E514B4549213EC');
        $this->addSql('ALTER TABLE property_view DROP FOREIGN KEY FK_E1E514B4A76ED395');
        $this->addSql('ALTER TABLE refund DROP FOREIGN KEY FK_5B2C14584C3A3BB');
        $this->addSql('ALTER TABLE refund DROP FOREIGN KEY FK_5B2C14582989F1FD');
        $this->addSql('ALTER TABLE refund DROP FOREIGN KEY FK_5B2C145838248176');
        $this->addSql('ALTER TABLE reset_password_request DROP FOREIGN KEY FK_7CE748AA76ED395');
        $this->addSql('ALTER TABLE subscription_email_log DROP FOREIGN KEY FK_34448A3F9A1887DC');
        $this->addSql('ALTER TABLE subscription_email_log DROP FOREIGN KEY FK_34448A3FCDEADB2A');
        $this->addSql('ALTER TABLE subscription_history DROP FOREIGN KEY FK_54AF90D09A1887DC');
        $this->addSql('ALTER TABLE subscription_history DROP FOREIGN KEY FK_54AF90D0CDEADB2A');
        $this->addSql('ALTER TABLE subscription_plan_price DROP FOREIGN KEY FK_5B8B2740E899029B');
        $this->addSql('ALTER TABLE subscription_plan_price DROP FOREIGN KEY FK_5B8B274038248176');
        $this->addSql('ALTER TABLE user_document_request DROP FOREIGN KEY FK_E2ED6B9EA76ED395');
        $this->addSql('ALTER TABLE user_document_request DROP FOREIGN KEY FK_E2ED6B9E837C14A7');
        $this->addSql('ALTER TABLE user_document_submission DROP FOREIGN KEY FK_50059ED7E3BD13F3');
        $this->addSql('ALTER TABLE user_document_submission DROP FOREIGN KEY FK_50059ED7FC6B21F1');
        $this->addSql('ALTER TABLE user_translation DROP FOREIGN KEY FK_1D728CFA2C2AC5D3');
        $this->addSql('ALTER TABLE `utilisateur` DROP FOREIGN KEY FK_1D1C63B3A6E44244');
        $this->addSql('ALTER TABLE `utilisateur` DROP FOREIGN KEY FK_1D1C63B328EAE92');
        $this->addSql('ALTER TABLE `utilisateur` DROP FOREIGN KEY FK_1D1C63B3F4445056');
        $this->addSql('ALTER TABLE `utilisateur` DROP FOREIGN KEY FK_1D1C63B398DBDF9B');
        $this->addSql('DROP TABLE agency_billing_profile');
        $this->addSql('DROP TABLE agency_notification');
        $this->addSql('DROP TABLE agency_payment_method');
        $this->addSql('DROP TABLE agency_profile_daily_visit');
        $this->addSql('DROP TABLE agency_subscription');
        $this->addSql('DROP TABLE agency_subscription_period');
        $this->addSql('DROP TABLE billing_tax_identifier');
        $this->addSql('DROP TABLE booster_pack');
        $this->addSql('DROP TABLE booster_pack_price');
        $this->addSql('DROP TABLE booster_transaction');
        $this->addSql('DROP TABLE caracteristique');
        $this->addSql('DROP TABLE caracteristique_translation');
        $this->addSql('DROP TABLE category_bien');
        $this->addSql('DROP TABLE category_bien_transaction');
        $this->addSql('DROP TABLE category_bien_transaction_translation');
        $this->addSql('DROP TABLE category_bien_translation');
        $this->addSql('DROP TABLE contact');
        $this->addSql('DROP TABLE credit_note');
        $this->addSql('DROP TABLE credit_note_line');
        $this->addSql('DROP TABLE devise');
        $this->addSql('DROP TABLE favoris');
        $this->addSql('DROP TABLE fuseau_horaire');
        $this->addSql('DROP TABLE horaire_ouverture');
        $this->addSql('DROP TABLE invoice');
        $this->addSql('DROP TABLE invoice_discount');
        $this->addSql('DROP TABLE invoice_line');
        $this->addSql('DROP TABLE invoice_tax');
        $this->addSql('DROP TABLE langue_parler');
        $this->addSql('DROP TABLE langue_parler_user');
        $this->addSql('DROP TABLE langues');
        $this->addSql('DROP TABLE maintenance_allowed_ip');
        $this->addSql('DROP TABLE maintenance_setting');
        $this->addSql('DROP TABLE payment');
        $this->addSql('DROP TABLE payment_attempt');
        $this->addSql('DROP TABLE payment_fee');
        $this->addSql('DROP TABLE payment_webhook_event');
        $this->addSql('DROP TABLE pays');
        $this->addSql('DROP TABLE property');
        $this->addSql('DROP TABLE property_caracteristique');
        $this->addSql('DROP TABLE property_boost');
        $this->addSql('DROP TABLE property_image');
        $this->addSql('DROP TABLE property_search_session');
        $this->addSql('DROP TABLE property_translation');
        $this->addSql('DROP TABLE property_view');
        $this->addSql('DROP TABLE refund');
        $this->addSql('DROP TABLE required_document');
        $this->addSql('DROP TABLE reset_password_request');
        $this->addSql('DROP TABLE subscription_email_log');
        $this->addSql('DROP TABLE subscription_history');
        $this->addSql('DROP TABLE subscription_plan');
        $this->addSql('DROP TABLE subscription_plan_price');
        $this->addSql('DROP TABLE translation');
        $this->addSql('DROP TABLE user_document_request');
        $this->addSql('DROP TABLE user_document_submission');
        $this->addSql('DROP TABLE user_translation');
        $this->addSql('DROP TABLE `utilisateur`');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
