flysystem:
    storages:
        avatars.storage:
            visibility: public
            local:
                directory: "%kernel.project_dir%/public/images/avatar"

        biens.storage:
            visibility: public
            local:
                directory: "%kernel.project_dir%/public/images/bien"