<?php

/**
 * Copyright(c)2026 Boolts (https://boolts.com)
 *
 * Ce fichier fait partie d’un projet développé par Auxioma Web Agency pour l’entreprise Pastelit Co.
 * Tous droits réservés.
 *
 * Ce code source est la propriété exclusive de Auxioma Web Agency et Pastelit Co.
 * Toute reproduction, modification, distribution ou utilisation sans autorisation préalable est interdite.
 */

namespace App\DataFixtures\RealEstate;

/**
 * Référentiel géographique fermé des annonces de démonstration.
 *
 * Les clés correspondent exclusivement aux champs réellement persistés par
 * Property et PropertyTranslation. Les coordonnées désignent le centre de la
 * commune ; PropertyFixtures applique ensuite un faible décalage déterministe.
 */
final class PropertyLocationCatalog
{
    /** @var list<array{countryCode: string, country: string, codePostal: string, ville: string, region: string, department: string, latitude: string, longitude: string, neighborhoods: list<string>}> */
    private const CITIES = [
        ['countryCode' => 'FR', 'country' => 'France', 'codePostal' => '75004', 'ville' => 'Paris', 'region' => 'Île-de-France', 'department' => 'Paris', 'latitude' => '48.8566', 'longitude' => '2.3522', 'neighborhoods' => ['Le Marais', 'Montmartre', 'Batignolles', 'Passy', 'Saint-Germain-des-Prés', 'Bastille', 'République', 'Belleville', 'Quartier Latin']],
        ['countryCode' => 'FR', 'country' => 'France', 'codePostal' => '13006', 'ville' => 'Marseille', 'region' => 'Provence-Alpes-Côte d’Azur', 'department' => 'Bouches-du-Rhône', 'latitude' => '43.2965', 'longitude' => '5.3698', 'neighborhoods' => ['Le Panier', 'Prado', 'Endoume', 'La Joliette', 'Castellane', 'Roucas-Blanc']],
        ['countryCode' => 'FR', 'country' => 'France', 'codePostal' => '69002', 'ville' => 'Lyon', 'region' => 'Auvergne-Rhône-Alpes', 'department' => 'Rhône', 'latitude' => '45.7640', 'longitude' => '4.8357', 'neighborhoods' => ['Presqu’île', 'Croix-Rousse', 'Part-Dieu', 'Vieux Lyon', 'Monplaisir']],
        ['countryCode' => 'FR', 'country' => 'France', 'codePostal' => '31000', 'ville' => 'Toulouse', 'region' => 'Occitanie', 'department' => 'Haute-Garonne', 'latitude' => '43.6047', 'longitude' => '1.4442', 'neighborhoods' => ['Capitole', 'Carmes', 'Saint-Cyprien', 'Compans-Caffarelli', 'Jolimont']],
        ['countryCode' => 'FR', 'country' => 'France', 'codePostal' => '06000', 'ville' => 'Nice', 'region' => 'Provence-Alpes-Côte d’Azur', 'department' => 'Alpes-Maritimes', 'latitude' => '43.7102', 'longitude' => '7.2620', 'neighborhoods' => ['Carré d’Or', 'Libération', 'Mont Boron', 'Cimiez', 'Port']],
        ['countryCode' => 'FR', 'country' => 'France', 'codePostal' => '44000', 'ville' => 'Nantes', 'region' => 'Pays de la Loire', 'department' => 'Loire-Atlantique', 'latitude' => '47.2184', 'longitude' => '-1.5536', 'neighborhoods' => ['Centre-ville', 'Île de Nantes', 'Procé', 'Chantenay', 'Saint-Félix']],
        ['countryCode' => 'FR', 'country' => 'France', 'codePostal' => '34000', 'ville' => 'Montpellier', 'region' => 'Occitanie', 'department' => 'Hérault', 'latitude' => '43.6108', 'longitude' => '3.8767', 'neighborhoods' => ['Écusson', 'Port Marianne', 'Beaux-Arts', 'Antigone', 'Boutonnet']],
        ['countryCode' => 'FR', 'country' => 'France', 'codePostal' => '67000', 'ville' => 'Strasbourg', 'region' => 'Grand Est', 'department' => 'Bas-Rhin', 'latitude' => '48.5734', 'longitude' => '7.7521', 'neighborhoods' => ['Petite France', 'Krutenau', 'Orangerie', 'Neudorf', 'Robertsau']],
        ['countryCode' => 'FR', 'country' => 'France', 'codePostal' => '33000', 'ville' => 'Bordeaux', 'region' => 'Nouvelle-Aquitaine', 'department' => 'Gironde', 'latitude' => '44.8378', 'longitude' => '-0.5792', 'neighborhoods' => ['Chartrons', 'Saint-Pierre', 'Caudéran', 'Bacalan', 'Nansouty']],
        ['countryCode' => 'FR', 'country' => 'France', 'codePostal' => '59000', 'ville' => 'Lille', 'region' => 'Hauts-de-France', 'department' => 'Nord', 'latitude' => '50.6292', 'longitude' => '3.0573', 'neighborhoods' => ['Vieux-Lille', 'Wazemmes', 'Vauban', 'Saint-Maurice', 'Fives']],
        ['countryCode' => 'FR', 'country' => 'France', 'codePostal' => '35000', 'ville' => 'Rennes', 'region' => 'Bretagne', 'department' => 'Ille-et-Vilaine', 'latitude' => '48.1173', 'longitude' => '-1.6778', 'neighborhoods' => ['Centre', 'Thabor', 'Sainte-Thérèse', 'Saint-Hélier', 'Villejean']],
        ['countryCode' => 'FR', 'country' => 'France', 'codePostal' => '51100', 'ville' => 'Reims', 'region' => 'Grand Est', 'department' => 'Marne', 'latitude' => '49.2583', 'longitude' => '4.0317', 'neighborhoods' => ['Centre-ville', 'Boulingrin', 'Clairmarais', 'Cernay', 'La Neuvillette']],
        ['countryCode' => 'FR', 'country' => 'France', 'codePostal' => '76600', 'ville' => 'Le Havre', 'region' => 'Normandie', 'department' => 'Seine-Maritime', 'latitude' => '49.4944', 'longitude' => '0.1079', 'neighborhoods' => ['Centre reconstruit', 'Saint-Vincent', 'Docks', 'Sainte-Cécile', 'Sanvic']],
        ['countryCode' => 'FR', 'country' => 'France', 'codePostal' => '42000', 'ville' => 'Saint-Étienne', 'region' => 'Auvergne-Rhône-Alpes', 'department' => 'Loire', 'latitude' => '45.4397', 'longitude' => '4.3872', 'neighborhoods' => ['Centre-ville', 'Bergson', 'Fauriel', 'Bellevue', 'Monthieu']],
        ['countryCode' => 'FR', 'country' => 'France', 'codePostal' => '83000', 'ville' => 'Toulon', 'region' => 'Provence-Alpes-Côte d’Azur', 'department' => 'Var', 'latitude' => '43.1242', 'longitude' => '5.9280', 'neighborhoods' => ['Le Mourillon', 'Haute Ville', 'Cap Brun', 'Saint-Jean-du-Var', 'Pont du Las']],
        ['countryCode' => 'FR', 'country' => 'France', 'codePostal' => '38000', 'ville' => 'Grenoble', 'region' => 'Auvergne-Rhône-Alpes', 'department' => 'Isère', 'latitude' => '45.1885', 'longitude' => '5.7245', 'neighborhoods' => ['Championnet', 'Île Verte', 'Europole', 'Berriat', 'Saint-Bruno']],
        ['countryCode' => 'FR', 'country' => 'France', 'codePostal' => '21000', 'ville' => 'Dijon', 'region' => 'Bourgogne-Franche-Comté', 'department' => 'Côte-d’Or', 'latitude' => '47.3220', 'longitude' => '5.0415', 'neighborhoods' => ['Centre historique', 'Toison d’Or', 'Montchapet', 'Darcy', 'Maladière']],
        ['countryCode' => 'FR', 'country' => 'France', 'codePostal' => '49000', 'ville' => 'Angers', 'region' => 'Pays de la Loire', 'department' => 'Maine-et-Loire', 'latitude' => '47.4784', 'longitude' => '-0.5632', 'neighborhoods' => ['La Doutre', 'Centre-ville', 'Madeleine', 'Justices', 'Lafayette']],
        ['countryCode' => 'FR', 'country' => 'France', 'codePostal' => '30000', 'ville' => 'Nîmes', 'region' => 'Occitanie', 'department' => 'Gard', 'latitude' => '43.8367', 'longitude' => '4.3601', 'neighborhoods' => ['Écusson', 'Jean Jaurès', 'Castanet', 'Garrigues', 'Puech du Teil']],
        ['countryCode' => 'FR', 'country' => 'France', 'codePostal' => '69100', 'ville' => 'Villeurbanne', 'region' => 'Auvergne-Rhône-Alpes', 'department' => 'Rhône', 'latitude' => '45.7719', 'longitude' => '4.8902', 'neighborhoods' => ['Gratte-Ciel', 'Charpennes', 'Cusset', 'République', 'Croix-Luizet']],
        ['countryCode' => 'FR', 'country' => 'France', 'codePostal' => '63000', 'ville' => 'Clermont-Ferrand', 'region' => 'Auvergne-Rhône-Alpes', 'department' => 'Puy-de-Dôme', 'latitude' => '45.7772', 'longitude' => '3.0870', 'neighborhoods' => ['Jaude', 'Salins', 'Montferrand', 'Les Carmes', 'Chamalières']],
        ['countryCode' => 'FR', 'country' => 'France', 'codePostal' => '13100', 'ville' => 'Aix-en-Provence', 'region' => 'Provence-Alpes-Côte d’Azur', 'department' => 'Bouches-du-Rhône', 'latitude' => '43.5297', 'longitude' => '5.4474', 'neighborhoods' => ['Mazarin', 'Rotonde', 'Saint-Mitre', 'La Torse', 'Jas de Bouffan']],
        ['countryCode' => 'FR', 'country' => 'France', 'codePostal' => '29200', 'ville' => 'Brest', 'region' => 'Bretagne', 'department' => 'Finistère', 'latitude' => '48.3904', 'longitude' => '-4.4861', 'neighborhoods' => ['Siam', 'Recouvrance', 'Saint-Marc', 'Lambézellec', 'Kerinou']],
        ['countryCode' => 'FR', 'country' => 'France', 'codePostal' => '37000', 'ville' => 'Tours', 'region' => 'Centre-Val de Loire', 'department' => 'Indre-et-Loire', 'latitude' => '47.3941', 'longitude' => '0.6848', 'neighborhoods' => ['Vieux-Tours', 'Les Halles', 'Grammont', 'Febvotte', 'Paul Bert']],
        ['countryCode' => 'FR', 'country' => 'France', 'codePostal' => '80000', 'ville' => 'Amiens', 'region' => 'Hauts-de-France', 'department' => 'Somme', 'latitude' => '49.8941', 'longitude' => '2.2958', 'neighborhoods' => ['Saint-Leu', 'Centre-ville', 'Henriville', 'Saint-Pierre', 'Faubourg de Hem']],
        ['countryCode' => 'FR', 'country' => 'France', 'codePostal' => '87000', 'ville' => 'Limoges', 'region' => 'Nouvelle-Aquitaine', 'department' => 'Haute-Vienne', 'latitude' => '45.8336', 'longitude' => '1.2611', 'neighborhoods' => ['Centre-ville', 'Cité', 'Beaublanc', 'Vanteaux', 'Montjovis']],
        ['countryCode' => 'FR', 'country' => 'France', 'codePostal' => '74000', 'ville' => 'Annecy', 'region' => 'Auvergne-Rhône-Alpes', 'department' => 'Haute-Savoie', 'latitude' => '45.8992', 'longitude' => '6.1294', 'neighborhoods' => ['Vieille Ville', 'Albigny', 'Courier', 'Novel', 'Cran-Gevrier']],
        ['countryCode' => 'FR', 'country' => 'France', 'codePostal' => '66000', 'ville' => 'Perpignan', 'region' => 'Occitanie', 'department' => 'Pyrénées-Orientales', 'latitude' => '42.6887', 'longitude' => '2.8948', 'neighborhoods' => ['Centre historique', 'Saint-Martin', 'Moulin à Vent', 'Las Cobas', 'Clodion']],
        ['countryCode' => 'FR', 'country' => 'France', 'codePostal' => '57000', 'ville' => 'Metz', 'region' => 'Grand Est', 'department' => 'Moselle', 'latitude' => '49.1193', 'longitude' => '6.1757', 'neighborhoods' => ['Nouvelle Ville', 'Centre historique', 'Queuleu', 'Sablon', 'Amphithéâtre']],
        ['countryCode' => 'FR', 'country' => 'France', 'codePostal' => '25000', 'ville' => 'Besançon', 'region' => 'Bourgogne-Franche-Comté', 'department' => 'Doubs', 'latitude' => '47.2378', 'longitude' => '6.0241', 'neighborhoods' => ['La Boucle', 'Chaprais', 'Battant', 'Saint-Claude', 'Velotte']],
        ['countryCode' => 'FR', 'country' => 'France', 'codePostal' => '45000', 'ville' => 'Orléans', 'region' => 'Centre-Val de Loire', 'department' => 'Loiret', 'latitude' => '47.9030', 'longitude' => '1.9093', 'neighborhoods' => ['Centre-ville', 'Dunois', 'Saint-Marceau', 'Madeleine', 'Carmes']],
        ['countryCode' => 'FR', 'country' => 'France', 'codePostal' => '76000', 'ville' => 'Rouen', 'region' => 'Normandie', 'department' => 'Seine-Maritime', 'latitude' => '49.4432', 'longitude' => '1.0993', 'neighborhoods' => ['Vieux-Marché', 'Saint-Sever', 'Jouvenet', 'Gare', 'Saint-Maclou']],
        ['countryCode' => 'FR', 'country' => 'France', 'codePostal' => '68100', 'ville' => 'Mulhouse', 'region' => 'Grand Est', 'department' => 'Haut-Rhin', 'latitude' => '47.7508', 'longitude' => '7.3359', 'neighborhoods' => ['Centre-ville', 'Rebberg', 'Dornach', 'Fonderie', 'Nouveau Bassin']],
        ['countryCode' => 'FR', 'country' => 'France', 'codePostal' => '14000', 'ville' => 'Caen', 'region' => 'Normandie', 'department' => 'Calvados', 'latitude' => '49.1829', 'longitude' => '-0.3707', 'neighborhoods' => ['Centre ancien', 'Vaucelles', 'Saint-Gilles', 'Beaulieu', 'Saint-Ouen']],
        ['countryCode' => 'FR', 'country' => 'France', 'codePostal' => '54000', 'ville' => 'Nancy', 'region' => 'Grand Est', 'department' => 'Meurthe-et-Moselle', 'latitude' => '48.6921', 'longitude' => '6.1844', 'neighborhoods' => ['Ville Vieille', 'Saurupt', 'Mon Désert', 'Rives de Meurthe', 'Boudonville']],
        ['countryCode' => 'FR', 'country' => 'France', 'codePostal' => '84000', 'ville' => 'Avignon', 'region' => 'Provence-Alpes-Côte d’Azur', 'department' => 'Vaucluse', 'latitude' => '43.9493', 'longitude' => '4.8055', 'neighborhoods' => ['Intra-muros', 'Banasterie', 'Saint-Ruf', 'Barthelasse', 'Montfavet']],
        ['countryCode' => 'FR', 'country' => 'France', 'codePostal' => '17000', 'ville' => 'La Rochelle', 'region' => 'Nouvelle-Aquitaine', 'department' => 'Charente-Maritime', 'latitude' => '46.1603', 'longitude' => '-1.1511', 'neighborhoods' => ['Vieux-Port', 'Les Minimes', 'La Genette', 'Saint-Éloi', 'Fétilly']],
        ['countryCode' => 'FR', 'country' => 'France', 'codePostal' => '06400', 'ville' => 'Cannes', 'region' => 'Provence-Alpes-Côte d’Azur', 'department' => 'Alpes-Maritimes', 'latitude' => '43.5528', 'longitude' => '7.0174', 'neighborhoods' => ['Croisette', 'Californie', 'Le Suquet', 'Palm Beach', 'Carnot']],
        ['countryCode' => 'FR', 'country' => 'France', 'codePostal' => '06600', 'ville' => 'Antibes', 'region' => 'Provence-Alpes-Côte d’Azur', 'department' => 'Alpes-Maritimes', 'latitude' => '43.5804', 'longitude' => '7.1251', 'neighborhoods' => ['Cap d’Antibes', 'Vieil Antibes', 'Juan-les-Pins', 'Fontonne', 'Combes']],
        ['countryCode' => 'FR', 'country' => 'France', 'codePostal' => '64200', 'ville' => 'Biarritz', 'region' => 'Nouvelle-Aquitaine', 'department' => 'Pyrénées-Atlantiques', 'latitude' => '43.4832', 'longitude' => '-1.5586', 'neighborhoods' => ['Centre', 'Côte des Basques', 'Saint-Charles', 'Beaurivage', 'La Négresse']],
        ['countryCode' => 'FR', 'country' => 'France', 'codePostal' => '20000', 'ville' => 'Ajaccio', 'region' => 'Corse', 'department' => 'Corse-du-Sud', 'latitude' => '41.9192', 'longitude' => '8.7386', 'neighborhoods' => ['Cours Napoléon', 'Sanguinaires', 'Vieille Ville', 'Mezzavia', 'Salines']],
        ['countryCode' => 'MA', 'country' => 'Maroc', 'codePostal' => '20000', 'ville' => 'Casablanca', 'region' => 'Casablanca-Settat', 'department' => 'Préfecture de Casablanca', 'latitude' => '33.5731', 'longitude' => '-7.5898', 'neighborhoods' => ['Maarif', 'Gauthier', 'Racine', 'Bourgogne', 'Ain Diab', 'Palmier', 'Californie', 'Sidi Maarouf']],
        ['countryCode' => 'MA', 'country' => 'Maroc', 'codePostal' => '10000', 'ville' => 'Rabat', 'region' => 'Rabat-Salé-Kénitra', 'department' => 'Préfecture de Rabat', 'latitude' => '34.0209', 'longitude' => '-6.8416', 'neighborhoods' => ['Agdal', 'Hay Riad', 'Hassan', 'Souissi', 'Océan', 'Aviation']],
        ['countryCode' => 'MA', 'country' => 'Maroc', 'codePostal' => '40000', 'ville' => 'Marrakech', 'region' => 'Marrakech-Safi', 'department' => 'Préfecture de Marrakech', 'latitude' => '31.6295', 'longitude' => '-7.9811', 'neighborhoods' => ['Guéliz', 'Hivernage', 'Palmeraie', 'Agdal', 'Médina', 'Targa']],
        ['countryCode' => 'MA', 'country' => 'Maroc', 'codePostal' => '30000', 'ville' => 'Fès', 'region' => 'Fès-Meknès', 'department' => 'Préfecture de Fès', 'latitude' => '34.0331', 'longitude' => '-5.0003', 'neighborhoods' => ['Ville Nouvelle', 'Agdal', 'Fès el Bali', 'Narjiss', 'Route d’Imouzzer']],
        ['countryCode' => 'MA', 'country' => 'Maroc', 'codePostal' => '90000', 'ville' => 'Tanger', 'region' => 'Tanger-Tétouan-Al Hoceïma', 'department' => 'Préfecture de Tanger-Assilah', 'latitude' => '35.7595', 'longitude' => '-5.8340', 'neighborhoods' => ['Malabata', 'Iberia', 'Centre-ville', 'Marshan', 'Californie']],
        ['countryCode' => 'MA', 'country' => 'Maroc', 'codePostal' => '80000', 'ville' => 'Agadir', 'region' => 'Souss-Massa', 'department' => 'Préfecture d’Agadir Ida-Outanane', 'latitude' => '30.4278', 'longitude' => '-9.5981', 'neighborhoods' => ['Founty', 'Talborjt', 'Sonaba', 'Haut Founty', 'Cité Suisse']],
        ['countryCode' => 'MA', 'country' => 'Maroc', 'codePostal' => '50000', 'ville' => 'Meknès', 'region' => 'Fès-Meknès', 'department' => 'Préfecture de Meknès', 'latitude' => '33.8935', 'longitude' => '-5.5473', 'neighborhoods' => ['Hamria', 'Ville Nouvelle', 'Médina', 'Marjane', 'Agdal']],
        ['countryCode' => 'MA', 'country' => 'Maroc', 'codePostal' => '60000', 'ville' => 'Oujda', 'region' => 'Oriental', 'department' => 'Préfecture d’Oujda-Angad', 'latitude' => '34.6814', 'longitude' => '-1.9086', 'neighborhoods' => ['Centre-ville', 'Hay Al Qods', 'Al Irfane', 'Isly', 'Sidi Yahya']],
        ['countryCode' => 'MA', 'country' => 'Maroc', 'codePostal' => '14000', 'ville' => 'Kénitra', 'region' => 'Rabat-Salé-Kénitra', 'department' => 'Province de Kénitra', 'latitude' => '34.2610', 'longitude' => '-6.5802', 'neighborhoods' => ['Maâmora', 'Centre-ville', 'Bir Rami', 'Val Fleury', 'Mimosas']],
        ['countryCode' => 'MA', 'country' => 'Maroc', 'codePostal' => '93000', 'ville' => 'Tétouan', 'region' => 'Tanger-Tétouan-Al Hoceïma', 'department' => 'Province de Tétouan', 'latitude' => '35.5785', 'longitude' => '-5.3684', 'neighborhoods' => ['Ensanche', 'Médina', 'Wilaya', 'Sania Ramel', 'Mhannech']],
        ['countryCode' => 'MA', 'country' => 'Maroc', 'codePostal' => '11000', 'ville' => 'Salé', 'region' => 'Rabat-Salé-Kénitra', 'department' => 'Préfecture de Salé', 'latitude' => '34.0531', 'longitude' => '-6.7985', 'neighborhoods' => ['Tabriquet', 'Hay Salam', 'Bettana', 'Médina', 'Sala Al Jadida']],
        ['countryCode' => 'MA', 'country' => 'Maroc', 'codePostal' => '24000', 'ville' => 'El Jadida', 'region' => 'Casablanca-Settat', 'department' => 'Province d’El Jadida', 'latitude' => '33.2316', 'longitude' => '-8.5007', 'neighborhoods' => ['Cité Portugaise', 'Centre-ville', 'Plage', 'Hay Al Matar', 'Najd']],
        ['countryCode' => 'MA', 'country' => 'Maroc', 'codePostal' => '28800', 'ville' => 'Mohammédia', 'region' => 'Casablanca-Settat', 'department' => 'Préfecture de Mohammédia', 'latitude' => '33.6866', 'longitude' => '-7.3829', 'neighborhoods' => ['Parc', 'Monica', 'Centre-ville', 'La Siesta', 'Wafa']],
        ['countryCode' => 'MA', 'country' => 'Maroc', 'codePostal' => '46000', 'ville' => 'Safi', 'region' => 'Marrakech-Safi', 'department' => 'Province de Safi', 'latitude' => '32.2994', 'longitude' => '-9.2372', 'neighborhoods' => ['Ville Nouvelle', 'Corniche', 'Médina', 'Plateau', 'Sidi Bouzid']],
        ['countryCode' => 'MA', 'country' => 'Maroc', 'codePostal' => '44000', 'ville' => 'Essaouira', 'region' => 'Marrakech-Safi', 'department' => 'Province d’Essaouira', 'latitude' => '31.5085', 'longitude' => '-9.7595', 'neighborhoods' => ['Médina', 'Borj', 'Plage', 'Azlef', 'Lotissement Azlef']],
        ['countryCode' => 'MA', 'country' => 'Maroc', 'codePostal' => '62000', 'ville' => 'Nador', 'region' => 'Oriental', 'department' => 'Province de Nador', 'latitude' => '35.1681', 'longitude' => '-2.9335', 'neighborhoods' => ['Centre-ville', 'Hay Al Matar', 'Marchica', 'Al Karm', 'Taouima']],
        ['countryCode' => 'MA', 'country' => 'Maroc', 'codePostal' => '23000', 'ville' => 'Beni Mellal', 'region' => 'Béni Mellal-Khénifra', 'department' => 'Province de Béni Mellal', 'latitude' => '32.3373', 'longitude' => '-6.3498', 'neighborhoods' => ['Centre-ville', 'Atlas', 'Hay Salam', 'Jbel Tassemit', 'Massira']],
        ['countryCode' => 'MA', 'country' => 'Maroc', 'codePostal' => '25000', 'ville' => 'Khouribga', 'region' => 'Béni Mellal-Khénifra', 'department' => 'Province de Khouribga', 'latitude' => '32.8811', 'longitude' => '-6.9063', 'neighborhoods' => ['Centre-ville', 'Al Qods', 'Hay El Amal', 'OCP', 'Laâyoune']],
        ['countryCode' => 'MA', 'country' => 'Maroc', 'codePostal' => '26000', 'ville' => 'Settat', 'region' => 'Casablanca-Settat', 'department' => 'Province de Settat', 'latitude' => '33.0010', 'longitude' => '-7.6166', 'neighborhoods' => ['Centre-ville', 'Mimouna', 'Hay El Qods', 'Al Fath', 'Mers Sultan']],
        ['countryCode' => 'MA', 'country' => 'Maroc', 'codePostal' => '53000', 'ville' => 'Ifrane', 'region' => 'Fès-Meknès', 'department' => 'Province d’Ifrane', 'latitude' => '33.5333', 'longitude' => '-5.1167', 'neighborhoods' => ['Centre-ville', 'Atlas', 'Université', 'Tizguit', 'Dayet Aoua']],
        ['countryCode' => 'MA', 'country' => 'Maroc', 'codePostal' => '32000', 'ville' => 'Al Hoceïma', 'region' => 'Tanger-Tétouan-Al Hoceïma', 'department' => 'Province d’Al Hoceïma', 'latitude' => '35.2517', 'longitude' => '-3.9372', 'neighborhoods' => ['Corniche', 'Centre-ville', 'Calabonita', 'Miramonte', 'Izemmouren']],
        ['countryCode' => 'MA', 'country' => 'Maroc', 'codePostal' => '73000', 'ville' => 'Dakhla', 'region' => 'Dakhla-Oued Ed-Dahab', 'department' => 'Province d’Oued Ed-Dahab', 'latitude' => '30.4107', 'longitude' => '-8.9017', 'neighborhoods' => ['Centre-ville', 'Hay Al Massira', 'Lagune', 'Al Qods', 'El Kassam']],
        ['countryCode' => 'MA', 'country' => 'Maroc', 'codePostal' => '70000', 'ville' => 'Laâyoune', 'region' => 'Laâyoune-Sakia El Hamra', 'department' => 'Province de Laâyoune', 'latitude' => '27.1253', 'longitude' => '-13.1625', 'neighborhoods' => ['Centre-ville', 'Al Wifaq', 'Moulay Rachid', 'Hay El Amal', 'Al Qods']],
    ];

    /** @return list<array{countryCode: string, country: string, codePostal: string, ville: string, region: string, department: string, latitude: string, longitude: string, neighborhoods: list<string>}> */
    public static function all(): array
    {
        return self::CITIES;
    }
}
